### PR TITLE
Add ability to configure a nginx `proxy_pass`

### PR DESCRIPTION
**Pull request by forkata**
This change adds the ability to configure simple nginx proxy_pass in
the custom json for an app, by specifying a list of hashes containing a `location` and
an `upstream`.

### CODE REVIEW

**Comment by Senjai** [comment]
Seems reasonable. I'm not sure if I'd call a list of proxy configurations proxy_pass, maybe proxies? Otherwise :+1:

**Comment by alexblackie** [comment]
LGTM :+1: I kind of like `proxy_passes`, describes what it is perfectly.

**Comment by forkata** [comment]
I originally had `proxy_passes` but changed to `proxy_pass`. I will update.

**Comment by Senjai** [comment]
:+1: :shipit:

**Pull request merged**
